#!/bin/bash
## v0.0.0

if ssh-add -L | grep macpc ; then
  echo ok # nothing
else
  ssh-add ~/.ssh/mac_id_rsa_2
fi

export version=`cat VERSION`
set -ex

./scripts/version_bump
./scripts/update_gemspec

bundle

gem build wco_hosting.gemspec
gem push wco_hosting-`cat VERSION`.gem
rm wco_hosting-`cat VERSION`.gem

git add .
git commit -m 'autobuild `date "+%Y%m%d"`' ;
git push

set +ex
echo "wco_hosting build ok"
